import { Box, CircleDollarSign, Coins, CreditCard, HandCoins, HandHeart, Handshake, House, IndianRupee, LucideSwatchBook, School, Shield, Sprout, Tractor, Trees, User } from "lucide-react";
import { useTranslation } from "react-i18next";

export const useFinancialProducts = (type = "all") => {
  const { t } = useTranslation();

  const allProducts = [
    // LOANS
    {
      id: "kisan-credit-card",
      type: "loan",
      name: 'Kisan Credit Card',
      title: t('kisanCreditCardLoan'),
      description: t('kisanCreditCardLoanDesc'),
      icon: CreditCard,
      color: "bg-green-100 text-green-700",
    },
    {
      id: "tractor-machinery-loan",
      type: "loan",
      name: 'Tractor Machinery Loan',
      title: t('tractorMachineryLoan'),
      description: t('tractorMachineryLoanDesc'),
      icon: Tractor,
      color: "bg-blue-100 text-blue-700",
    },
    {
      id: "crop-loan",
      type: "loan",
      name: 'Crop Loan',
      title: t('cropLoan'),
      description: t('cropLoanDesc'),
      icon: Sprout,
      color: "bg-green-100 text-green-700",
    },
    {
      id: "dairy-livestock-loan",
      type: "loan",
      name: 'Dairy Livestock Loan',
      title: t('dairyLivestockLoan'),
      description: t('dairyLivestockLoanDesc'),
      icon: LucideSwatchBook,
      color: "bg-yellow-100 text-yellow-700",
    },
    {
      id: "farm-development-loan",
      type: "loan",
      name: 'Farm Development Loan',
      title: t('farmDevelopmentLoan'),
      description: t('farmDevelopmentLoanDesc'),
      icon: Trees,
      color: "bg-blue-100 text-blue-700",
    },
    {
      id: "agri-gold-loan",
      type: "loan",
      name: 'Agri Gold Loan',
      title: t('agriGoldLoan'),
      description: t('agriGoldLoanDesc'),
      icon: Coins,
      color: "bg-yellow-100 text-yellow-700",
    },

    {
      id: "savings-account",
      type: "account",
      title: t('savingsAccount'),
      description: t('savingsAccountDesc'),
      icon: HandCoins,
      color: "bg-green-100 text-green-700",
    },
    {
      id: "salary-account",
      type: "account",
      title: t('salaryAccount'),
      description: t('salaryAccountDesc'),
      icon: CircleDollarSign,
      color: "bg-blue-100 text-blue-700",
    },
    {
      id: "current-account",
      type: "account",
      title: t('currentAccount'),
      description: t('currentAccountDesc'),
      icon: IndianRupee,
      color: "bg-purple-100 text-purple-700",
    },
    {
      id: "safe-deposit-locker",
      type: "account",
      title: t('safeDepositLocker'),
      description: t('safeDepositLockerDesc'),
      icon: Box,
      color: "bg-green-100 text-green-700",
    },
    {
      id: "safe-custody",
      type: "account",
      title: t('safeCustody'),
      description: t('safeCustodyDesc'),
      icon: Shield,
      color: "bg-blue-100 text-blue-700",
    },
    {
      id: "sukanya-samriddhi",
      type: "account",
      title: t('sukanyaSamriddhi'),
      description: t('sukanyaSamriddhiDesc'),
      icon: HandHeart,
      color: "bg-purple-100 text-purple-700",
    },
    {
      id: "pmfby",
      type: "insurance",
      name: 'PMFBY',
      title: t('pmfby'),
      description: t('pmfbyDesc'),
      icon: HandCoins,
      color: "bg-green-100 text-green-700",
    },
    {
      id: "wbcis",
      type: "insurance",
      name: 'Weather-Based Crop Insurance Scheme',
      title: t('wbcis'),
      description: t('wbcisDesc'),
      icon: CircleDollarSign,
      color: "bg-blue-100 text-blue-700",
    },
    {
      id: "livestock-insurance",
      type: "insurance",
      name: 'Livestock Insurance',
      title: t('livestockInsurance'),
      description: t('livestockInsuranceDesc'),
      icon: IndianRupee,
      color: "bg-purple-100 text-purple-700",
    },
    {
      id: "farm-machinery-insurance",
      type: "insurance",
      name: 'Farm Machinery Insurance',
      title: t('farmMachineryInsurance'),
      description: t('farmMachineryInsuranceDesc'),
      icon: Box,
      color: "bg-green-100 text-green-700",
    },
    {
      id: "personal-accident-insurance",
      type: "insurance",
      name: 'Personal Accident Insurance',
      title: t('personalAccidentInsurance'),
      description: t('personalAccidentInsuranceDesc'),
      icon: Shield,
      color: "bg-blue-100 text-blue-700",
    },
    {
      id: "horticulture-insurance",
      type: "insurance",
      name: 'Horticulture Insurance',
      title: t('horticultureInsurance'),
      description: t('horticultureInsuranceDesc'),
      icon: HandHeart,
      color: "bg-purple-100 text-purple-700",
    },

    // MARKETPLACE DEMO PRODUCTS
    {
      id: "seed-purchase",
      type: "marketplace",
      name: "Seeds",
      title: t("marketplaceSeeds") || "High-Yield Seeds",
      description: t("marketplaceSeedsDesc") || "Buy certified, quality seeds for your crops.",
      icon: Sprout,
      color: "bg-yellow-100 text-yellow-700",
    },
    {
      id: "fertilizer-purchase",
      type: "marketplace",
      name: "Fertilizers",
      title: t("marketplaceFertilizers") || "Organic & Chemical Fertilizers",
      description: t("marketplaceFertilizersDesc") || "Shop a wide range of fertilizers for soil health.",
      icon: Handshake,
      color: "bg-green-100 text-green-700",
    },
    {
      id: "agri-machinery-rental",
      type: "marketplace",
      name: "Machinery Rental",
      title: t("marketplaceMachinery") || "Agri-Machinery Rental",
      description: t("marketplaceMachineryDesc") || "Rent tractors, tillers, and other agricultural equipment.",
      icon: Tractor,
      color: "bg-blue-100 text-blue-700",
    },
    {
      id: "crop-sell",
      type: "marketplace",
      name: "Sell Crops",
      title: t("marketplaceSellCrop") || "Sell Your Harvest",
      description: t("marketplaceSellCropDesc") || "Connect to buyers or local mandis to sell your crops.",
      icon: Box,
      color: "bg-orange-100 text-orange-700",
    },
    {
      id: "farm-services",
      type: "marketplace",
      name: "Farm Services",
      title: t("marketplaceServices") || "Farm Labour & Services",
      description: t("marketplaceServicesDesc") || "Find planting, harvesting, irrigation and drone-spraying services.",
      icon: User,
      color: "bg-purple-100 text-purple-700",
    },
  ];

  if (type === "all") return allProducts;
  else return allProducts.filter((product) => product.type === type);
};
